# Mark Shust's Magento 2 Docker Compose (https://github.com/markoshust/magento2-docker)
# Version 10.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-4
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - appdata:/var/www/html
    ports:
      - 8000:80
    networks: &appnetworks
      - www

  phpfpm:
    image: markoshust/magento-php:7.1-fpm-8
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks

  db:
    image: percona:5.7
    ports:
      - 8001:3306
    networks: *appnetworks
    env_file: docker/env/mysql.env

  setup:
    image: markoshust/magento-php:7.1-fpm-8
    command: /usr/local/bin/mage-setup
    links:
      - db
    volumes: *appvolumes
    networks: *appnetworks
    env_file: docker/env/setup.env

volumes:
  appdata:

networks:
  www: